# Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)


# Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np
vec = np.arange(10, 50)


print(vec)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Create a 3x3 matrix with values ranging from 0 to 8 

In [3]:
import numpy as np

mat = np.arange(9).reshape(3, 3)

print(mat)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
import numpy as np


arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4], dtype=int64),)


# Create a 10x10 array with random values and find the minimum and maximum values.

In [9]:
import numpy as np
arr = np.random.rand(10, 10)
min_val = arr.min()
max_val = arr.max()

print("Minimum value:", min_val)
print("Maximum value:", max_val)


Minimum value: 0.006067118892391532
Maximum value: 0.9995206284909744


# Create a random vector of size 30 and find the mean value.


In [10]:
import numpy as np

vec = np.random.rand(30)
mean_val = vec.mean()

print("Mean value:", mean_val)


Mean value: 0.4922968146987478
